DROP DATABASE IF EXISTS BIL_495;
CREATE SCHEMA BIL_495; 
USE BIL_495;

DROP TABLE IF EXISTS 
	USER,
	 RECIPE,
	 PHOTO;
                     
CREATE TABLE USER (
	name VARCHAR(20)  NOT NULL,
	pass VARCHAR(20) NOT NULL,
	PRIMARY KEY(name)
	) DEFAULT CHARSET=utf8mb4;
CREATE TABLE RECIPE (
	recipe_id INTEGER(6) NOT NULL AUTO_INCREMENT,
	user_name VARCHAR(20) NOT NULL,    
	content VARCHAR(400) NOT NULL,
	title VARCHAR(20)  NOT NULL,
	viewers VARCHAR(40) NOT NULL,
	like_amount INT NOT NULL DEFAULT 0,
	UNIQUE KEY (title),
	PRIMARY KEY(recipe_id),
	CONSTRAINT fk_user FOREIGN KEY (user_name) REFERENCES USER(name) ON DELETE CASCADE
	) DEFAULT CHARSET=utf8mb4;
CREATE TABLE PHOTO (user_name VARCHAR(20)  NOT NULL,
	id_recipe INTEGER(6) NOT NULL,
	ph BLOB NOT NULL,
	CONSTRAINT fk_photo_user FOREIGN KEY (user_name) REFERENCES USER(name) ON DELETE CASCADE,
	CONSTRAINT fk_recipe_id FOREIGN KEY (id_recipe) REFERENCES RECIPE(recipe_id) ON DELETE CASCADE
	)DEFAULT CHARSET=utf8mb4;
  